// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTotalVideoCount(arg1:string):Promise<number>;

export function GetVersion():Promise<string>;

export function GetVideoFiles(arg1:string,arg2:number,arg3:number):Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function StartUpdateCheck():Promise<void>;

export function StartVideoServer(arg1:string):Promise<number>;
